FROM node:18-alpine as production
WORKDIR /app
COPY node_modules /app/node_modules
COPY ./dist /app/dist
COPY package.json .env ./
RUN yarn install --production
CMD ["node", "dist/src/main.js"]
EXPOSE 3002