FROM node:18-alpine as production
ENV NODE_ENV production
WORKDIR /app
COPY package.json tsconfig.json .env ./
RUN yarn install --production
RUN yarn build
CMD ["node", "dist/src/main.js"]
EXPOSE 3002