version: "3"

services:
  mission-commander-service:
      image: mission-commander
      restart: always
      ports:
        - "3006:3006"
      networks:
      - rocket-network

networks:
  rocket-network:
    external: true