version: "3"

services:
  rocket-service:
    image: rocket-status
    restart: always
    ports:
      - "3001:3001"
    networks:
      - rocket-network

networks:
  rocket-network:
    external: true
      