FROM node:18-alpine
WORKDIR /app
ENV NODE_ENV production
COPY package.json tsconfig.json .env ./
COPY dist ./dist
RUN yarn install --production --frozen-lockfile
CMD ["node", "dist/src/main.js"]
EXPOSE 3001