FROM node:18-alpine
ENV NODE_ENV production
WORKDIR /app
COPY package.json tsconfig.json .env ./
RUN yarn install --production --frozen-lockfile
RUN yarn build
CMD ["node", "dist/src/main.js"]
EXPOSE 3001