version: "3"

services:
  telemetrie-service:
      image: telemetrie
      restart: always
      depends_on:
        - mongo_db_telemetrics
      ports:
        - "3003:3003"
      networks:
        - nestjs-telemetrics-mongo
        - rocket-network
  mongo_db_telemetrics:
    image: "mongo:5.0.0"
    restart: always
    ports:
      - 27018:27017
    networks:
      - nestjs-telemetrics-mongo
      
      

networks:
  nestjs-telemetrics-mongo:
    driver: bridge
  rocket-network:
    name: rocket-network
    driver: bridge