version: "3"

services:
  rocket-object-service:
    image: rocket-object-service
    restart: always
    ports:
      - "3005:3005"
    networks:
      - rocket-network

networks:
  rocket-network:
    external: true