version: "3"

services:
  payload-service:
      image: payload-status
      restart: always
      depends_on:
        - mongo_db_payload_telemetrics
      ports:
        - "3004:3004"
      networks:
        - rocket-network
        - nestjs-payload-telemetrics-mongo
  mongo_db_payload_telemetrics:
    image: "mongo:5.0.0"
    restart: always
    ports:
      - 27019:27017
    networks:
      - nestjs-payload-telemetrics-mongo


networks:
  nestjs-payload-telemetrics-mongo:
    driver: bridge
  rocket-network:
    external: true
      