version: "3"

services:
  payload-service:
      image: payload-status
      restart: always
      ports:
        - "3004:3004"
      networks:
        - rocket-network


networks:
  rocket-network:
    external: true
      