name: Testing rocket department

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Running tests for rocket status controller
        run: cd rocket-department/rocket-department && yarn && yarn test